### ISSUE TITLE
3.0.1: setuptools build_sphinx command fails

### ISSUE THREAD

**Issue by kloczek** [zopefoundation/transaction#104]
AFAIK it is not possible to specify in setup.cfg in `[build_sphinx]` section base path to module.
If I'm right this could be solved by move `src/transaction/` to `transaction/`
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/transaction-3.0.1/docs/conf.py", line 22, in <module>
    rqmt = pkg_resources.require('transaction')[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'transaction' distribution was not found and is required by the application
```
And after copy `src/transaction*` to root directory
```comnsole
[tkloczko@barrel transaction-3.0.1]$ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2

Extension error:
Could not import extension repoze.sphinx.autointerface (exception: No module named 'repoze')
```
And here is another esmall problem because `repoze` module requires on testing `transaction` and `transaction` requires on building documentation `repoze.sphinx.autointerface` (which is part of `repoze`).
It is kind of cyrcular dependency :/
IMO it would be good to rewrite  `transaction`  documentation using only plain `sphinx`.

**Comment by d-maurer** [comment]
Tomasz Kłoczko wrote at 2021-6-4 06:55 -0700:
>AFAIK it is not possible to specify in setup.cfg in `[build_sphinx]` section base path to module.
>If I'm right this could be solved by move `src/transaction/` to `transaction/`

Almost all `zopefoundation` projects have the primary source below `src`.
Thus, there should be a solution for documentation generation
without moving `src/transaction` to `transaction`.

**Comment by kloczek** [comment]
I just found kind of workaround ..
```console
$ PYTHONPATH=$PWD/src /usr/bin/python3 setup.py build_sphinx -b man
```
Nevertheless if it is possible to do that other way by tweaking somehow source tree IMO it would be good to implemt that 😊

What about drop `repoze.sphinx.autointerface` dependency? 🥺
IIRC sphinx provides OOTB some functionalities to generate API documentation ..🤔
In my packages I'm trying to not have cyrcular dependencies or at leeast minimise such non-planar dependencies by any cost.

**Comment by jugmac00** [comment]
`repoze.sphinx.autointerface` is necessary to document Interfaces via zope.interfaces.

I have not looked at the source, though.

**Comment by d-maurer** [comment]
Tomasz Kłoczko wrote at 2021-6-4 07:29 -0700:
>Nevertheless if it is possible to do that other way by tweaking somehow source tree IMO it would be good to implemt that ?


Please keep the `src` directory (for consistency with most
other `zopefoundation` projects).

**Comment by mgedmin** [comment]
Sometimes distribution packagers object to using tox because their builds have to work offline, and tox wants to install dependencies directly from PyPI.

In which case the answer is to look at what commands `tox.ini` runs (which is `sphinx-build`) and do that.

**Comment by kloczek** [comment]
In mean time I found workaround for that case by execute `PYTHONPATH=$PWD/build/lib /usr/bin/python3 setup.py build_sphinx -b man`.
However instead forcing to use tox I think that better would be just add that path in copy.py to sys.path (many modules does that to handle correctly build_sphinx).

**Comment by mgedmin** [comment]
We're not interested in supporting `python setup.py build_sphinx`.  The Python packaging ecosystem is slowly moving away from `setup.py` files with PEP-517 builds etc.

**Comment by kloczek** [comment]
OK. So how to build documentation using pep517?

**Comment by mgedmin** [comment]
Run `sphinx-build`.

**Comment by kloczek** [comment]
```console
[tkloczko@barrel transaction-3.0.1]$ sphinx-build
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build: error: the following arguments are required: sourcedir, outputdir, filenames
```
Of course that is wrong execution and few parametres are missing. However unig that way you must know wres is source code and where is copy.py ..
So using pep517 it is not possible to run arbitrarry command like in case setuptools.
Just checked one more time how it is with pep517 ..
```console
[tkloczko@barrel SPECS]$ ls -1 /usr/lib/python3.8/site-packages/pep517
build.py
check.py
colorlog.py
compat.py
dirtools.py
envbuild.py
__init__.py
in_process
meta.py
__pycache__
wrappers.py
````
and looks like pep517 still cannot do maaany things which setuptools is able to organise.
I've checked ~450 of my python rpm packages and only handfull packages are using pep517.
```console
[tkloczko@barrel SPECS]$ grep pep517 * -l
python-black.spec
python-build.spec
python-pep517.spec
python-poetry-core.spec
python-pytest-checkdocs.spec
```
To to much better situation is in case Fedora (where is packaged more than 2.4k python modules)
```console
[tkloczko@barrel SPECS.fedora]$ grep pep517 * -l 
pipenv.spec
pipx.spec
pypy.spec
python2.7.spec
python-asyncpg.spec
python-chaospy.spec
python-check-manifest.spec
python-nashpy.spec
python-niaaml.spec
python-niaclass.spec
python-pep517.spec
python-pip.spec
python-poetry-core.spec
python-sklearn-nature-inspired-algorithms.spec
python-sport-activities-features.spec
````
Amongd those ~450 python mpacjages:
```console
[tkloczko@barrel SPECS]$ grep "python3dist(setuptools)" python-* | wc -l
434
```
I would really suggest stick with setuptools (at least for now) because pep517 still is in very embrionic/early development state.
