### ISSUE TITLE
Unicode change in 2.0.3 breaking waitress

### ISSUE THREAD

**Issue by niothiel** [zopefoundation/transaction#34]
I just discovered this in the past hour. I'm running an instance of [PyPiCloud](http://pypicloud.readthedocs.io/en/latest/) via waitress on python 2.7. Any time a request is received, this is the stack trace:

```
ERROR 2016-11-17 21:45:52,515 [waitress] Exception when serving /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pyramid_tm/__init__.py", line 85, in tm_tween
    t.note(native_(request.path_info, 'utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/transaction/_transaction.py", line 539, in note
    raise TypeError("Note must be text (unicode)")
TypeError: Note must be text (unicode)
```

Using version 2.0.2 works. I managed to track it down to a change made as part of the 2.0.3 release:

https://github.com/zopefoundation/transaction/compare/2.0.2...2.0.3#diff-b65460bed0b38b3a42d05ce9c3b22f1eR537

**Comment by tseaver** [comment]
It isn't *waitress* which is broken by the change, but rather `pyramid_tm`, which is forcibly passing a "native" string to `transaction.note()`.

**Comment by jamadden** [comment]
See https://github.com/Pylons/pyramid_tm/issues/49

**Comment by niothiel** [comment]
I see. Is there any intention of modifying this functionality? Maybe coercing any passed-in `str` into `unicode`?

**Comment by mmerickel** [comment]
This should be fixed in pyramid_tm 1.1.0. Let me know if it isn't but this issue can probably be closed. Open an issue in the pyramid_tm repository if you're still having problems.

**Comment by tseaver** [comment]
@niothiel Please check that the new `pyramid_tm` release resolves your issue, and close this issue if so.

**Comment by niothiel** [comment]
Tested with `pyramid_tm==1.1.1`. Resolved.
